### ISSUE TITLE
Ошибка при вызове метода контекста (Открыть), Каталог не обнаружен 'C:\Program Files (x86)\VideoLAN\VLC\NEWS.txt'

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#399]
ОС: Windows 7 (32bit)
VB: 1.030

`{ВнешняяОбработка.РаботаСВидео.Форма.Форма.Форма(1635)}: Ошибка при вызове метода контекста (Открыть)
	Текст.Открыть(ИмяФайла,"UTF-8");
по причине:
Каталог не обнаружен 'C:\Program Files (x86)\VideoLAN\VLC\NEWS.txt'`

**Comment by Pr-Mex** [comment]
Похоже винда 32 битная

**Comment by nixel2007** [comment]
Хардкодить пути вообще не ок)

**Comment by Pr-Mex** [comment]
Это точно )

**Comment by Pr-Mex** [comment]
Сонар мне напишет, что что-то не так?

**Comment by nixel2007** [comment]
Нет, этот репо не подключён. 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "Pautov Leonid" <notifications@github.com>
Кому: "silverbulleters/vanessa-behavior" <vanessa-behavior@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>, "Comment" <comment@noreply.github.com>
Тема: [silverbulleters/vanessa-behavior] Ошибка при вызове метода контекста (Открыть), Каталог не обнаружен 'C:\Program Files (x86)\VideoLAN\VLC\NEWS.txt' (#399)
Дата: пт, сент. 16, 2016 18:00

Сонар мне напишет, что что-то не так?

&mdash;You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.










{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/silverbulleters/vanessa-behavior","title":"silverbulleters/vanessa-behavior","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/silverbulleters/vanessa-behavior"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pr-Mex in #399: Сонар мне напишет, что что-то не так?"}],"action":{"name":"View Issue","url":"https://github.com/silverbulleters/vanessa-behavior/issues/399#issuecomment-247623347"}}}

**Comment by Pr-Mex** [comment]
В другом репо тот же код.

**Comment by nixel2007** [comment]
Что ты ожидаешь увидеть в ответе сонара?

**Comment by Pr-Mex** [comment]
Я хочу увидеть:
Строка кода такая-то - указан явный путь к приложению.
Он так может?

**Comment by nixel2007** [comment]
Пока нет, но научить не сложно. Идея хорошая, запишу

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
